config/routes.rb
# first created -> highest priority.
Eol::Application.routes.draw do

  # Root should be first, since it's most frequently used and should return quickly:
  root :to => 'content#index'
  
  #resque
  mount Resque::Server.new, at: "/resque"
  # Permanent redirects. Position them before any routes they take precedence over.
  match '/podcast' => redirect('http://podcast.eol.org/podcast')
  match '/pages/:taxon_id/curators' => redirect("/pages/%{taxon_id}/community/curators")
  match '/pages/:taxon_id/images' => redirect("/pages/%{taxon_id}/media")
  match '/pages/:taxon_id/classification_attribution' => redirect("/pages/%{taxon_id}/names")
  match '/pages/:taxon_id/entries/:entry_id' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/overview")
  match '/pages/:taxon_id/entries/:entry_id/overview' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/overview")
  match '/pages/:taxon_id/entries/:entry_id/details' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/details")
  match '/pages/:taxon_id/classification_attribution' => redirect("/pages/%{taxon_id}/names")
  match '/pages/:taxon_id/community' => redirect("/pages/%{taxon_id}/communities")
  match '/pages/:taxon_id/community/collections' => redirect("/pages/%{taxon_id}/communities/collections")
  match '/pages/:taxon_id/community/curators' => redirect("/pages/%{taxon_id}/communities/curators")
  match '/pages/:taxon_id/hierarchy_entries/:entry_id/community' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/communities")
  match '/pages/:taxon_id/hierarchy_entries/:entry_id/community/collections' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/communities/collections")
  match '/pages/:taxon_id/hierarchy_entries/:entry_id/community/curators' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/communities/curators")
  match '/taxa/content/:taxon_id' => redirect("/pages/%{taxon_id}/details")
  match '/taxa/images/:taxon_id' => redirect("/pages/%{taxon_id}/media")
  match '/taxa/maps/:taxon_id' => redirect("/pages/%{taxon_id}/maps")
  match '/settings' => redirect("/")
  match '/account/show/:user_id' => redirect("/users/%{user_id}")
  match '/users/forgot_password' => redirect("/users/recover_account")
  match '/users/:user_id/reset_password/:recover_account_token' => redirect("/users/recover_account")
  match '/info/xrayvision' => redirect("/collections/14770")
  match '/info/brian-skerry' => redirect("/collections/29285")
  match '/info/naturesbest2011' => redirect("/collections/19338")
  match '/info/naturesbest2012' => redirect("/collections/54659")
  match '/info/naturesbest2013' => redirect("/collections/103870")
  match '/voc/table_of_contents' => redirect("/schema/eol_info_items.xml")
  match '/voc/table_of_contents#:term' => redirect("/schema/eol_info_items.xml%{term}")
  match '/index' => redirect('/')
  match '/home.html' => redirect('/')
  match '/favicon' => redirect('/assets/favicon.ico')
  match '/forum' => redirect('/forums'), :as => 'forum_redirect'
  match '/schema/terms/:id' => 'schema#terms', :as => 'schema_terms'

  # Taxa nested resources with pages as alias... this is quite large, sorry. Please keep it high in the routes file,
  # since it's 90% of the website.  :)
  resources :pages, :only => [:show], :controller => 'taxa', :as => 'taxa' do
    resource :overview, :only => [:show], :controller => 'taxa/overview'
    resource :tree, :only => [:show], :controller => 'taxa/trees'
    resources :maps, :only => [:index], :controller => 'taxa/maps'
    resources :media, :only => [:show], :controller => 'taxa/media'
    resources :details, :except => [:show], :controller => 'taxa/details'
    resource :worklist, :only => [:show], :controller => 'taxa/worklist'
    resources :data_objects, :only => [:create, :new]
    resource :taxon_concept_reindexing, :as => 'reindexing', :only => [:create],
      :controller => 'taxa/taxon_concept_reindexing'
    resources :data, :only => [:index], :controller => 'taxa/data' do
      collection do
        get 'about'
        get 'glossary'
        get 'ranges'
      end
    end
    resources :hierarchy_entries, :as => 'entries', :only => [:show] do
      member do
        put 'switch'
      end
      resource :overview, :only => [:show], :controller => 'taxa/overview'
      resource :tree, :only => [:show], :controller => 'taxa/trees'
      resources :maps, :only => [:index], :controller => 'taxa/maps'
      resources :media, :only => [:index], :controller => 'taxa/media'
      resources :details, :only => [:index], :controller => 'taxa/details'
      resources :data, :only => [:index], :controller => 'taxa/data' do
        collection do
          get 'about'
          get 'glossary'
          get 'ranges'
        end
      end
      resources :communities, :only => [:index], :controller => 'taxa/communities' do
        collection do
          get 'collections'
          get 'curators'
        end
      end
      resources :names, :only => [:index, :create, :update], :controller => 'taxa/names' do
        collection do
          get 'common_names'
          get 'related_names'
          get 'synonyms'
          get 'delete'
        end
        member do
          get 'vet_common_name'
        end
      end
      resource :literature, :only => [:show], :controller => 'taxa/literature' do
        collection do
          get 'bhl'
          get 'literature_links'
        end
      end
      resources :resources, :only => [:index], :controller => 'taxa/resources' do
        collection do
          get 'partner_links'
          get 'identification_resources'
          get 'education'
          get 'nucleotide_sequences'
          get 'biomedical_terms'
          get 'citizen_science'
          get 'news_and_event_links'
          get 'related_organizations'
          get 'multimedia_links'
        end
      end
      resources :updates, :only => [:index], :controller => 'taxa/updates' do
        collection do
          get 'statistics'
        end
      end
    end
    resources :media, :only => [:index], :controller => 'taxa/media'
    resources :names, :only => [:index, :create, :update], :controller => 'taxa/names' do
      collection do
        get 'common_names'
        get 'related_names'
        get 'synonyms'
        get 'delete'
      end
      member do
        get 'vet_common_name'
      end
    end
    resource :literature, :only => [:show], :controller => 'taxa/literature' do
      collection do
        get 'bhl'
        get 'literature_links'
      end
    end
    resources :resources, :controller => 'taxa/resources', :only => [:index] do
      collection do
        get 'partner_links'
        get 'identification_resources'
        get 'education'
        get 'nucleotide_sequences'
        get 'biomedical_terms'
        get 'citizen_science'
        get 'news_and_event_links'
        get 'related_organizations'
        get 'multimedia_links'
      end
    end
    resources :communities, :only => [:index], :controller => 'taxa/communities' do
      collection do
        get 'collections'
        get 'curators'
      end
    end
    resources :updates, :only => [:index], :controller => 'taxa/updates' do
      collection do
        get 'statistics'
      end
    end
  end

  # Communities nested resources
  # TODO - these member methods want to be :put. Capybara always uses :get, so in the interests of simple tests:
  resources :communities, :except => [:index] do
    collection do
      get 'choose'
      put 'make_editors'
    end
    member do
      get 'join'
      get 'leave'
      get 'delete'
      put 'make_editor'
      get 'revoke_editor'
    end
    resource :newsfeed, :only => [:show], :controller => 'communities/newsfeeds'
    resources :collections, :controller => 'communities/collections'
    resources :members do
      member do
        # TODO - these shouldn't be GETs, but I really want them to be links, not forms, sooooo...
        get 'grant_manager'
        get 'revoke_manager'
      end
    end
  end

  resources :collections do
    member do
      get 'choose'
      get 'reindex'
    end
    collection do
      get 'get_name'
      get 'get_uri_name'
      get 'cache_inaturalist_projects'
      get 'choose_collect_target'
      get 'choose_editor_target'
      get 'choose_taxa_data'
      post 'collect_item'
      post 'download_taxa_data'
    end
    resource :newsfeed, :only => [:show], :controller => 'collections/newsfeeds'
    resources :editors, :only => [:index], :controller => 'collections/editors'
    resource :inaturalist, :only => [:show], :controller => 'collections/inaturalists'
  end

  resources :collection_jobs, :only => [:create]

  resources :content_partners do
    member do
      post 'new'
    end
    resources :content_partner_contacts, :as => 'contacts', :except => [:index, :show], :controller => 'content_partners/content_partner_contacts' do
      member do
        delete 'delete'
      end
    end
    resources :content_partner_agreements, :as => 'agreements', :except => [:index, :destroy],
      :controller => 'content_partners/content_partner_agreements'
    resource :statistics, :only => [:show], :controller => 'content_partners/statistics'
    resources :resources, :controller => 'content_partners/resources' do
      member do
        get 'force_harvest', :controller => 'content_partners/resources'
        post 'force_harvest', :controller => 'content_partners/resources'
      end
      resources :harvest_events, :only => [:index, :update], :controller => 'content_partners/resources/harvest_events'
      resources :hierarchies, controller: 'content_partners/resources/hierarchies', only: [:edit, :update]  do
        member do
          post 'request_publish', :controller => 'content_partners/resources/hierarchies'
        end
      end
    end
  end

  resources :users, :path_names => { :new => :register } do
    member do
      get 'terms_agreement'
      post 'terms_agreement'

app/models/collection_type.rb
# I'm not entirely sure what this is, but it has something to do with outlinks to content partners. You'll see it being used by
# #hierarchy_outlink_collection_types, which is a helper method, and that's used on the taxa resources / partners tab.
#
# TODO - explain this class.  :\  ...Or remove it.
class CollectionType < ActiveRecord::Base
  uses_translations
  acts_as_tree order: 'lft'
  
  has_and_belongs_to_many :collections
  
  def materialized_path_labels

    parent_path = (parent_id == 0 || parent.nil?) ? '' : parent.materialized_path_labels + ' ('
    return parent_path + label + ((parent_id == 0 || parent.nil?) ? '' : ')')

  end
  
end

app/controllers/collections/editors_controller.rb
class Collections::EditorsController < CollectionsController

  skip_before_filter :user_able_to_edit_collection
  skip_before_filter :build_collection_items

  layout 'collections'

  def index
    @rel_canonical_href = collection_editors_url(@collection)
    # This aids in the views and in the methods from the parent controller:
    @filter = params[:filter] = 'editors'
  end

end

app/controllers/collections/inaturalists_controller.rb
class Collections::InaturalistsController < CollectionsController

  skip_before_filter :user_able_to_edit_collection
  skip_before_filter :build_collection_items

  layout 'collections'

  def show
    @inaturalist_project_id = @collection.inaturalist_project_info['id']
    @inaturalist_project_title = @collection.inaturalist_project_info['title']
    @inaturalist_observed_taxa_count = @collection.inaturalist_project_info['observed_taxa_count']
    if @inaturalist_project_id
      @inaturalist_project_observations = inaturalist_project_observations(@inaturalist_project_id)
    end
    # This aids in the views and in the methods from the parent controller:
    @filter = params[:filter] = 'inaturalist'
    if logged_in? && (authentications = current_user.open_authentications)
      @embed_auth_provider = "auth_provider=#{authentications.first.provider}" unless authentications.blank?
    end
  end

private

  def inaturalist_project_observations(project_id)
    return nil if project_id.nil?
    return nil if project_id == "[DATA MISSING]" # TODO - lame. We should have a way to express this.  :|
    url = "http://www.inaturalist.org/observations/project/#{project_id}.json?per_page=20"
    response = Net::HTTP.get(URI.parse(url))
    JSON.parse(response)
  end

end

app/controllers/collections/newsfeeds_controller.rb
class Collections::NewsfeedsController < CollectionsController

  skip_before_filter :user_able_to_edit_collection
  skip_before_filter :build_collection_items

  layout 'collections'

  def show
    @activity_log = @collection.activity_log(page: @page, user: current_user)
    set_canonical_urls(for: @collection, paginated: @activity_log, url_method: :collection_newsfeed_url)
    # This aids in the views and in the methods from the parent controller:
    @filter = params[:filter] = 'newsfeed'
  end

end

app/controllers/communities/collections_controller.rb
class Communities::CollectionsController < CommunitiesController

  # These are required because the declaration in CommunitiesController excludes index (for a good reason):
  before_filter :load_community_and_dependent_vars, only: [:index]
  # TODO - when the commands are added, the login should be required and the restrictions should be placed.  See
  # CommunitiesController.

  def index
    @community_collections = @community_collections.sort_by(&:created_at)
    @community_collections.reverse! if params[:sort_by] == 'oldest'
    @rel_canonical_href = community_collections_url(@community)
  end

end

app/controllers/users/collections_controller.rb
class Users::CollectionsController < UsersController

  skip_before_filter :extend_for_open_authentication

  # GET /users/:user_id/collections
  def index
    @user = User.find(params[:user_id])
    redirect_if_user_is_inactive
    preload_user_associations
    @published_collections = @user.published_collections(current_user)
    sort_by = params[:sort_by] && params[:sort_by].to_sym
    @sorts = {
      I18n.t(:sort_by_alphabetical_option) => :alpha,
      I18n.t(:sort_by_reverse_alphabetical_option) => :rev,
      I18n.t(:sort_by_newest_option) => :newest,
      I18n.t(:sort_by_oldest_option) => :oldest
    }
    if sort_by == :rev
      @published_collections.reverse!
    elsif sort_by == :oldest
      @published_collections = @published_collections.sort_by { |c| c.created_at.to_i } # NOTE - to_i required; otherwise "comparison of NilClass"
    elsif sort_by == :newest
      @published_collections = @published_collections.sort_by { |c| - c.created_at.to_i }
    end
    @rel_canonical_href = user_collections_url(@user)
    respond_to do |format|
      format.html {}
      format.json do
        render(
          json: @published_collections.as_json()
        )
      end
    end
  end

end

app/views/collections/_choose_collect_target.html.haml
#choose_collections
  - if @items
    -# NOTE - @for can either be 'copy' or 'move'.
    %h2= I18n.t("#{@for}_items_to_a_new_collection_with_count", :count => @items.count)
  - else
    %h2= raw(I18n.t(:add_item_to_new_collection, :item => sanitize(@item.summary_name)))
  = form_for Collection.new do |collection_form|
    - if @selected_collection_items
      - @selected_collection_items.each do |collection_item_id|
        = hidden_field_tag "collection_items[]", collection_item_id, :id => "collection_item_#{collection_item_id}"
    - if @items
      = hidden_field_tag :for, @for
      = hidden_field_tag :source_collection_id, @collection.id
      = hidden_field_tag :scope, @scope
    - else
      = hidden_field_tag :item_id, @item.id
      = hidden_field_tag :item_type, @item.class.name
    %fieldset.new_collection
      - # TODO: Refactor this. This is not accessible and also not using the activerecord error handling.
      %p.collection_name_error= I18n.t(:collection_name_cannot_be_blank)
      = collection_form.label :name, I18n.t(:collection_name_label), {:class => 'assistive'}
      = collection_form.text_field :name
      = submit_tag I18n.t(:create_collection_button), :class => 'button'
  - @collections ||= []
  -# Note the reject simply disallows you from collecting a collection in itself:
  - collections = @collections.reject {|c| @collection && c.id == @collection.id }
  - unless collections.empty?
    - form_target = @items ? @collection : CollectionItem.new(:collected_item => @item)
    = form_for(form_target) do |f|
      - if @selected_collection_items
        - @selected_collection_items.each do |collection_item_id|
          = hidden_field_tag "collection_items[]", collection_item_id, :id => "collection_item_#{collection_item_id}"
      - if @items
        = hidden_field_tag :for, @for
        = hidden_field_tag :source_collection_id, @collection.id
        = hidden_field_tag :scope, @scope
      - else
        = f.hidden_field :collected_item_id
        = f.hidden_field :collected_item_type
      - if @items
        %h2= I18n.t("or_#{@for}_them_to_existing_collection")
      - else
        %h2= I18n.t(:or_add_it_to_an_existing_collection)
      %fieldset
        %ul
          = render 'collections_list_item', { :collection => current_user.watch_collection, :has_item => current_user.watch_collection.has_item?(@item) }
          - collections.reject {|c| c.id == current_user.watch_collection.id }.each do |collection|
            = render 'collections_list_item', { :collection => collection, :has_item => collection.has_item?(@item) }
      %fieldset.actions
        = link_to(I18n.t(:see_all_of_your_collections), user_collections_path(current_user), :class => 'other_actions close_and_go')
        = submit_tag(params[:for] ? I18n.t(params[:for]) : I18n.t(:collect_item))
        - if @item || params[:return_to]
          = link_to(I18n.t(:go_back), params[:return_to] || link_to_item(@item), :class => 'close')

app/views/collections/_choose_editor_target.html.haml
#choose_collections
  %h2= @page_title # NOTE this is redundant and should likely be changed.
  - @collections ||= []
  -# Note the reject simply disallows you from collecting a collection in itself:
  - unless @collections.empty?
    - path = nil
    - path = make_editor_user_path(@user) if @user
    - path = make_editor_community_path(@community) if @community
    = form_tag(path, :method => :put) do |f|
      - one_available = false
      %fieldset
        %ul
          - @collections.each do |collection|
            - has_item = @item.can_edit_collection?(collection)
            - one_available = true unless has_item
            = render 'collections_list_item', { :collection => collection,
              :has_item => has_item, :hide_has_item => true }
      %fieldset.actions
        = link_to(I18n.t(:see_all_of_your_collections), user_collections_path(current_user),
          :class => 'other_actions close_and_go')
        - if one_available
          - if @user 
            = submit_tag(I18n.t(:make_an_editor))
          - else
            = submit_tag(I18n.t(:share_a_collection))
        - else
          %p
            %strong= I18n.t(:sorry_no_collections_are_available_to_share)
          %br
        - if @item
          = link_to(I18n.t(:go_back), link_to_item(@item), :class => 'close')

app/views/collections/_collection_summary.html.haml
- show_description ||= false
- minimal ||= false
%li.collection
  = link_to image_tag(collection.logo_url, :alt => collection.name), collection
  - if minimal
    = link_to collection.name, collection
  - else
    %h4
      = link_to collection.name, collection
      - if collection.communities.count == 1
        - community = collection.communities.first
        &bull;
        = raw(I18n.t(:from_community, :community => link_to(truncate(community.name, :length => 64), community)))
      - elsif collection.communities.count > 1
        &bull;
        = raw(I18n.t(:from_communities, :communities => collection.communities.map {|community| link_to(truncate(community.name, :length => 64), community) }.to_sentence ))
    = I18n.t(:items_with_count_semi_colon, :count => collection.collection_items_count)
    = I18n.t(:last_updated_time_ago, :time_passed => time_ago_in_words(collection.updated_at))
    - if maintainers = collection.maintained_by
      = I18n.t(:maintained_by)
      = raw(collection.maintained_by.map {|by| link_to truncate(by.summary_name, :length => 64), link_to_item(by) }.to_sentence)
    - if local_assigns.has_key?(:annotation) && !annotation.blank?
      %p= annotation

app/views/collections/_collections_list_item.html.haml
- hide_has_item ||= false
%li{:class => has_item ? 'collected' : nil}
  = check_box_tag 'collection_id[]', collection.id, has_item, :disabled => has_item
  = label_tag('collection_name', h(truncate(collection.name, :length => 64)))
  - if collection.communities || has_item || collection.id == current_user.watch_collection.id
    %span
      - if collection.communities.count == 1
        - community = collection.communities.first
        \&bull;
        = raw(I18n.t(:from_community, :community => link_to(truncate(community.name, :length => 64), community_path(community))))
      - elsif collection.communities.count > 1
        \&bull;
        = raw(I18n.t(:from_communities, :communities => collection.communities.map {|community| link_to(truncate(community.name, :length => 64), community_path(community)) }.to_sentence ))
      - if collection.id == current_user.watch_collection.id
        \&bull;
        = I18n.t(:your_watch_collection)
      - if has_item && ! hide_has_item
        \&bull;
        = raw(link_to(I18n.t(:in_collection), collection_url(collection), :class => 'close_and_go'))

app/views/collections/_editable_actions.html.haml
-# This is put in a comment here for convenience... so developers and those "in the know" can check the value.
/
  = "relevance #{@collection.relevance}"
- if editable
  - unless @collection.special?
    %li= link_to I18n.t(:add_to_a_community), choose_communities_path(:collection_id => @collection), :class => 'button'
  %li= link_to I18n.t(:edit_collection_details), edit_collection_path(@collection), :class => 'button'

app/views/collections/_managed_by.html.haml
- unless @filter == 'editors' # You don't need to show this, if we're viewing editors.
  %h3= I18n.t(:managed_by)
  %ul
    - editors = collection.maintained_by
    - editors[0..3].each do |thing|
      %li
        - if thing.is_a? Community
          = link_to image_tag(thing.logo_url, :alt => '', width: 35, height: 35), thing
          %h4= link_to thing.name, thing
        - elsif thing.is_a? User
          = link_to image_tag(thing.logo_url(size: :small), :alt => '', width: 35, height: 35), thing
          %h4= link_to thing.full_name, thing
          %p= thing.tag_line
    - if editors.length > 4
      %li= link_to(I18n.t(:see_all_editors_with_count, :count => editors.length), "/collections/#{@collection.id}/editors")

app/views/collections/_show_annotated_style.html.haml
- editable ||= false
%ul#collection_items.object_list
  - @collection_items.each do |item|
    - item_type = en_type(item)
    %li{class: item_type, id: "collection_item_#{item.id}"}
      = render 'collection_items/show', { :collection_item => item, :item_type => item_type,
        :view_style => 'annotated', :item_editable => editable, 
        is_hidden: ['image_map', 'map', 'image', 'video', 'sound', 'link', 'article'].include?(item_type) && item.is_hidden?  }

app/views/collections/_show_gallery_style.html.haml
%ul#collection_items.collection_gallery
  - @collection_items.each_with_index do |item, index|
    - item_type = en_type(item)
    %li{:class => "#{index.modulo(5) == 0 ? 'first' : nil} #{item_type}".strip}
      = render 'collection_items/show', { collection_item: item, item_type: item_type, view_style: 'gallery', 
        is_hidden: ['image_map', 'map', 'image', 'video', 'sound', 'link', 'article'].include?(item_type) && item.is_hidden? }

app/views/collections/_show_list_style.html.haml
%ul#collection_items.collection_names
  - @collection_items.each do |item|
    - item_type = en_type(item)
    %li{:class => item_type}
      = render 'collection_items/show', { collection_item: item, item_type: item_type, view_style: 'list', 
        is_hidden: ['image_map', 'map', 'image', 'video', 'sound', 'link', 'article'].include?(item_type) && item.is_hidden? }

app/views/collections/choose.html.haml
= render 'choose_collect_target'

app/views/collections/choose_collect_target.html.haml
= render 'choose_collect_target'

app/views/collections/choose_editor_target.html.haml
= render 'choose_editor_target'

app/views/collections/choose_taxa_data.html.haml
= stylesheet_link_tag 'taxon_collection'
= javascript_include_tag 'choose_taxa_data'
#taxon_collection
  - if @taxon_collected_items.blank?
    .empty
      %p= raw I18n.t('users.data_downloads.empty_taxa_collection')
  - else
    = form_tag(download_taxa_data_collections_path(collection_id: @collection), method: :post) do |f|
      %table#sortable.standard.taxon_collection
        %thead
          %tr.header
            %th= check_box_tag 'select_all', I18n.t("collections.download_taxa_data.select_all_checkbox")
            %th= I18n.t("collections.download_taxa_data.attribute_header")
        %tbody
          - @taxon_collected_items.each do |taxon_item|
            %fieldset
              %tr{ id: "taxon_collection_#{taxon_item.id}" }
                %td= check_box_tag 'data_point_uri[]', taxon_item.id
                %td
                  %span
                    = get_name(taxon_item.predicate)
                    - info_icon
      = will_paginate @taxon_collected_items
      = submit_tag I18n.t(:create_download_data_file)

app/views/collections/unpublished.html.haml
%h1.notice= I18n.t(:collection_was_removed_by_owner)