config/routes.rb
# first created -> highest priority.
Eol::Application.routes.draw do

  # Root should be first, since it's most frequently used and should return quickly:
  root :to => 'content#index'
  
  #resque
  mount Resque::Server.new, at: "/resque"
  # Permanent redirects. Position them before any routes they take precedence over.
  match '/podcast' => redirect('http://podcast.eol.org/podcast')
  match '/pages/:taxon_id/curators' => redirect("/pages/%{taxon_id}/community/curators")
  match '/pages/:taxon_id/images' => redirect("/pages/%{taxon_id}/media")
  match '/pages/:taxon_id/classification_attribution' => redirect("/pages/%{taxon_id}/names")
  match '/pages/:taxon_id/entries/:entry_id' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/overview")
  match '/pages/:taxon_id/entries/:entry_id/overview' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/overview")
  match '/pages/:taxon_id/entries/:entry_id/details' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/details")
  match '/pages/:taxon_id/classification_attribution' => redirect("/pages/%{taxon_id}/names")
  match '/pages/:taxon_id/community' => redirect("/pages/%{taxon_id}/communities")
  match '/pages/:taxon_id/community/collections' => redirect("/pages/%{taxon_id}/communities/collections")
  match '/pages/:taxon_id/community/curators' => redirect("/pages/%{taxon_id}/communities/curators")
  match '/pages/:taxon_id/hierarchy_entries/:entry_id/community' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/communities")
  match '/pages/:taxon_id/hierarchy_entries/:entry_id/community/collections' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/communities/collections")
  match '/pages/:taxon_id/hierarchy_entries/:entry_id/community/curators' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/communities/curators")
  match '/taxa/content/:taxon_id' => redirect("/pages/%{taxon_id}/details")
  match '/taxa/images/:taxon_id' => redirect("/pages/%{taxon_id}/media")
  match '/taxa/maps/:taxon_id' => redirect("/pages/%{taxon_id}/maps")
  match '/settings' => redirect("/")
  match '/account/show/:user_id' => redirect("/users/%{user_id}")
  match '/users/forgot_password' => redirect("/users/recover_account")
  match '/users/:user_id/reset_password/:recover_account_token' => redirect("/users/recover_account")
  match '/info/xrayvision' => redirect("/collections/14770")
  match '/info/brian-skerry' => redirect("/collections/29285")
  match '/info/naturesbest2011' => redirect("/collections/19338")
  match '/info/naturesbest2012' => redirect("/collections/54659")
  match '/info/naturesbest2013' => redirect("/collections/103870")
  match '/voc/table_of_contents' => redirect("/schema/eol_info_items.xml")
  match '/voc/table_of_contents#:term' => redirect("/schema/eol_info_items.xml%{term}")
  match '/index' => redirect('/')
  match '/home.html' => redirect('/')
  match '/favicon' => redirect('/assets/favicon.ico')
  match '/forum' => redirect('/forums'), :as => 'forum_redirect'
  match '/schema/terms/:id' => 'schema#terms', :as => 'schema_terms'

  # Taxa nested resources with pages as alias... this is quite large, sorry. Please keep it high in the routes file,
  # since it's 90% of the website.  :)
  resources :pages, :only => [:show], :controller => 'taxa', :as => 'taxa' do
    resource :overview, :only => [:show], :controller => 'taxa/overview'
    resource :tree, :only => [:show], :controller => 'taxa/trees'
    resources :maps, :only => [:index], :controller => 'taxa/maps'
    resources :media, :only => [:show], :controller => 'taxa/media'
    resources :details, :except => [:show], :controller => 'taxa/details'
    resource :worklist, :only => [:show], :controller => 'taxa/worklist'
    resources :data_objects, :only => [:create, :new]
    resource :taxon_concept_reindexing, :as => 'reindexing', :only => [:create],
      :controller => 'taxa/taxon_concept_reindexing'
    resources :data, :only => [:index], :controller => 'taxa/data' do
      collection do
        get 'about'
        get 'glossary'
        get 'ranges'
      end
    end
    resources :hierarchy_entries, :as => 'entries', :only => [:show] do
      member do
        put 'switch'
      end
      resource :overview, :only => [:show], :controller => 'taxa/overview'
      resource :tree, :only => [:show], :controller => 'taxa/trees'
      resources :maps, :only => [:index], :controller => 'taxa/maps'
      resources :media, :only => [:index], :controller => 'taxa/media'
      resources :details, :only => [:index], :controller => 'taxa/details'
      resources :data, :only => [:index], :controller => 'taxa/data' do
        collection do
          get 'about'
          get 'glossary'
          get 'ranges'
        end
      end
      resources :communities, :only => [:index], :controller => 'taxa/communities' do
        collection do
          get 'collections'
          get 'curators'
        end
      end
      resources :names, :only => [:index, :create, :update], :controller => 'taxa/names' do
        collection do
          get 'common_names'
          get 'related_names'
          get 'synonyms'
          get 'delete'
        end
        member do
          get 'vet_common_name'
        end
      end
      resource :literature, :only => [:show], :controller => 'taxa/literature' do
        collection do
          get 'bhl'
          get 'literature_links'
        end
      end
      resources :resources, :only => [:index], :controller => 'taxa/resources' do
        collection do
          get 'partner_links'
          get 'identification_resources'
          get 'education'
          get 'nucleotide_sequences'
          get 'biomedical_terms'
          get 'citizen_science'
          get 'news_and_event_links'
          get 'related_organizations'
          get 'multimedia_links'
        end
      end
      resources :updates, :only => [:index], :controller => 'taxa/updates' do
        collection do
          get 'statistics'
        end
      end
    end
    resources :media, :only => [:index], :controller => 'taxa/media'
    resources :names, :only => [:index, :create, :update], :controller => 'taxa/names' do
      collection do
        get 'common_names'
        get 'related_names'
        get 'synonyms'
        get 'delete'
      end
      member do
        get 'vet_common_name'
      end
    end
    resource :literature, :only => [:show], :controller => 'taxa/literature' do
      collection do
        get 'bhl'
        get 'literature_links'
      end
    end
    resources :resources, :controller => 'taxa/resources', :only => [:index] do
      collection do
        get 'partner_links'
        get 'identification_resources'
        get 'education'
        get 'nucleotide_sequences'
        get 'biomedical_terms'
        get 'citizen_science'
        get 'news_and_event_links'
        get 'related_organizations'
        get 'multimedia_links'
      end
    end
    resources :communities, :only => [:index], :controller => 'taxa/communities' do
      collection do
        get 'collections'
        get 'curators'
      end
    end
    resources :updates, :only => [:index], :controller => 'taxa/updates' do
      collection do
        get 'statistics'
      end
    end
  end

  # Communities nested resources
  # TODO - these member methods want to be :put. Capybara always uses :get, so in the interests of simple tests:
  resources :communities, :except => [:index] do
    collection do
      get 'choose'
      put 'make_editors'
    end
    member do
      get 'join'
      get 'leave'
      get 'delete'
      put 'make_editor'
      get 'revoke_editor'
    end
    resource :newsfeed, :only => [:show], :controller => 'communities/newsfeeds'
    resources :collections, :controller => 'communities/collections'
    resources :members do
      member do
        # TODO - these shouldn't be GETs, but I really want them to be links, not forms, sooooo...
        get 'grant_manager'
        get 'revoke_manager'
      end
    end
  end

  resources :collections do
    member do
      get 'choose'
      get 'reindex'
    end
    collection do
      get 'get_name'
      get 'get_uri_name'
      get 'cache_inaturalist_projects'
      get 'choose_collect_target'
      get 'choose_editor_target'
      get 'choose_taxa_data'
      post 'collect_item'
      post 'download_taxa_data'
    end
    resource :newsfeed, :only => [:show], :controller => 'collections/newsfeeds'
    resources :editors, :only => [:index], :controller => 'collections/editors'
    resource :inaturalist, :only => [:show], :controller => 'collections/inaturalists'
  end

  resources :collection_jobs, :only => [:create]

  resources :content_partners do
    member do
      post 'new'
    end
    resources :content_partner_contacts, :as => 'contacts', :except => [:index, :show], :controller => 'content_partners/content_partner_contacts' do
      member do
        delete 'delete'
      end
    end
    resources :content_partner_agreements, :as => 'agreements', :except => [:index, :destroy],
      :controller => 'content_partners/content_partner_agreements'
    resource :statistics, :only => [:show], :controller => 'content_partners/statistics'
    resources :resources, :controller => 'content_partners/resources' do
      member do
        get 'force_harvest', :controller => 'content_partners/resources'
        post 'force_harvest', :controller => 'content_partners/resources'
      end
      resources :harvest_events, :only => [:index, :update], :controller => 'content_partners/resources/harvest_events'
      resources :hierarchies, controller: 'content_partners/resources/hierarchies', only: [:edit, :update]  do
        member do
          post 'request_publish', :controller => 'content_partners/resources/hierarchies'
        end
      end
    end
  end

  resources :users, :path_names => { :new => :register } do
    member do
      get 'terms_agreement'
      post 'terms_agreement'

app/controllers/taxa/communities_controller.rb
class Taxa::CommunitiesController < TaxaController

  before_filter :instantiate_taxon_page, :redirect_if_superceded, :instantiate_preferred_names

  def index
    @communities = @taxon_concept.communities
    @assistive_section_header = I18n.t(:assistive_taxon_community_header)
    @rel_canonical_href = taxon_communities_url(@taxon_page)
  end

  def collections
    @collections = @taxon_concept.collections.select{ |c| c.published? && !c.watch_collection? }
    @assistive_section_header = I18n.t(:assistive_taxon_community_header)
    @rel_canonical_href = collections_taxon_communities_url(@taxon_page)
  end

  def curators
    @curators = @taxon_concept.data_object_curators
    @assistive_section_header = I18n.t(:assistive_taxon_community_header)
    @rel_canonical_href = curators_taxon_communities_url(@taxon_page)
  end

end

app/controllers/taxa/data_controller.rb
class Taxa::DataController < TaxaController

  helper DataSearchHelper # Because we include one of its partials.

  before_filter :instantiate_taxon_page, :redirect_if_superceded, :instantiate_preferred_names
  before_filter :load_data
  before_filter :load_glossary

  # GET /pages/:taxon_id/data/index
  def index
    EOL.log_call
    @assistive_section_header = I18n.t(:assistive_data_header)
    @recently_used = KnownUri.where(uri: session[:rec_uris]) if
      session[:rec_uris]
    @selected_data_point_uri_id = params.delete(:data_point_uri_id)
    if params[:toc_id].nil?
      @toc_id = 'ranges' if @data_point_uris.blank? && !@range_data.blank?
    else
      @toc_id = params[:toc_id]
      @toc_id = nil unless @toc_id == 'other' ||
        @categories.detect { |toc| toc.id.to_s == @toc_id }
    end

    @querystring = ''
    @sort = ''
    EOL.log("building jsonld")
    @jsonld = @taxon_data.jsonld
    EOL.log("#index done, rendering")
  end

  # GET /pages/:taxon_id/data/about
  def about
    @toc_id = 'about'
  end

  # GET /pages/:taxon_id/data/glossary
  def glossary
    @toc_id = 'glossary'
  end

  # GET /pages/:taxon_id/data/ranges
  def ranges
    @toc_id = 'ranges'
  end

protected

  def meta_description
    @taxon_data.topics
    translation_vars = scoped_variables_for_translations.dup
    translation_vars[:topics] = @taxon_data.topics.join("; ") unless @taxon_data.topics.empty?
    I18n.t("meta_description#{translation_vars[:topics] ? '_with_topics' : '_no_data'}", translation_vars)
  end

  def load_data
    EOL.log_call
    # Sad that we need to load all of this for the about and glossary tabs, but
    # TODO - we can cache this, later:
    @taxon_data = @taxon_page.data
    EOL.log("ranges_of_values", prefix: '.')
    @range_data = @taxon_data.ranges_of_values
    EOL.log("get_data", prefix: '.')
    @data_point_uris = @taxon_page.data.get_data
    EOL.log("for_uris", prefix: '.')
    @categories = TocItem.for_uris(current_language).
      select { |toc| @taxon_data.categories.include?(toc) }
    EOL.log("include_other_category", prefix: '.')
    @include_other_category = @data_point_uris &&
      @data_point_uris.detect { |d| d.predicate_known_uri.nil? ||
        d.predicate_known_uri.toc_items.blank? }
    EOL.log("default_units_for_form_select", prefix: '.')
    @units_for_select = KnownUri.default_units_for_form_select
  end

  def load_glossary
    @glossary_terms = @data_point_uris ?
      ( @data_point_uris.select{ |dp| ! dp.predicate_known_uri.blank? }.collect(&:predicate_known_uri) +
        @data_point_uris.select{ |dp| ! dp.object_known_uri.blank? }.collect(&:object_known_uri) +
        @data_point_uris.select{ |dp| ! dp.unit_of_measure_known_uri.blank? }.collect(&:unit_of_measure_known_uri) +
        @range_data.collect{ |r| r[:attribute] }).compact.uniq
      : []
  end

end

app/controllers/taxa/details_controller.rb
class Taxa::DetailsController < TaxaController

  before_filter :instantiate_taxon_page, :redirect_if_superceded, :instantiate_preferred_names

  # GET /pages/:taxon_id/details
  def index
    with_master_if_curator do
      @details = @taxon_page.details
    end
    @show_add_link_buttons = true
    @assistive_section_header = I18n.t(:assistive_details_header)
    @rel_canonical_href = taxon_details_url(@taxon_page)
  end

  # TODO - this doesn't belong here.
  def set_article_as_exemplar
    unless current_user && current_user.min_curator_level?(:assistant)
      
      raise EOL::Exceptions::SecurityViolation.new("User does not have set_article_as_exemplar privileges", :missing_set_article_as_exemplar_privilege)
      return
    end
    @taxon_concept = TaxonConcept.find(params[:taxon_id].to_i) rescue nil
    @data_object = DataObject.find_by_id(params[:data_object_id].to_i) rescue nil

    if @taxon_concept && @data_object
      TaxonConceptExemplarArticle.set_exemplar(@taxon_concept.id, @data_object.id)
      log_action(@taxon_concept, @data_object, :choose_exemplar_article)
    end

    store_location(params[:return_to] || request.referer)
    @taxon_concept.reload # This clears caches as well as any vars in memory.
    redirect_back_or_default taxon_details_path @taxon_concept.id
  end

protected
  def meta_description
    chapter_list = @details.chapter_list
    translation_vars = scoped_variables_for_translations.dup
    translation_vars[:chapter_list] = chapter_list.join("; ") unless chapter_list.blank?
    I18n.t("meta_description#{translation_vars[:preferred_common_name] ? '_with_common_name' :
           ''}#{translation_vars[:chapter_list] ? '_with_chapter_list' : '_no_data'}",
           translation_vars)
  end
  def meta_keywords
    keywords = super
    toc_subjects = @details.chapter_list.join(", ")
    [keywords, toc_subjects].compact.join(', ')
  end
  
end

app/controllers/taxa/literature_controller.rb
class Taxa::LiteratureController < TaxaController
  before_filter :instantiate_taxon_page, :redirect_if_superceded, :instantiate_preferred_names
  before_filter :literature_links_contents

  def show
    @references = Ref.find_refs_for(@taxon_concept.id)
    @references = Ref.sort_by_full_reference(@references)
    @assistive_section_header = I18n.t(:assistive_literature_header)
    @rel_canonical_href = taxon_literature_url(@taxon_page)
  end

  def bhl
    @assistive_section_header = I18n.t(:assistive_literature_header)
    @sort = params[:sort_by]
    @page = params[:page]
    @sort = 'year' unless ['title', 'title_desc', 'year', 'year_desc'].include?(@sort)
    @bhl_results = EOL::Solr::BHL.search(@taxon_concept, sort: @sort, page: @page)

    set_canonical_urls(for: @taxon_page, paginated: @bhl_results[:results],
                       url_method: :bhl_taxon_literature_url)
  end

  def bhl_title
    @title_item_id = params[:title_item_id]
    unless @title_item_id && @title_item_id.is_numeric?
      redirect_to bhl_taxon_literature_path(@taxon_concept)
    end
    @assistive_section_header = I18n.t(:assistive_literature_header)
    @bhl_title_results = EOL::Solr::BHL.search_publication(@taxon_concept, @title_item_id)
    # TODO: user natural sort to sort numerically, also romain numerals... not by string
    @rel_canonical_href = bhl_title_url(@taxon_page, @title_item_id)
  end

  def literature_links
    @assistive_section_header = I18n.t(:literature_links)
    @add_article_toc_id = nil
    @add_link_type_id = LinkType.paper ? LinkType.paper.id : nil
    @show_add_link_buttons = @add_link_type_id
    @rel_canonical_href = literature_links_taxon_literature_url(@taxon_page)
  end
  
  def literature_links_contents
    @literature_links_contents ||= @taxon_page.text(
      language_ids: [ current_language.id ],
      link_type_ids: [ LinkType.paper.id ]
    )
  end

end

app/views/taxa/literature/_bhl_header.html.haml
.bhl_description
  = image_tag 'v2/logo_bhl.png', alt: I18n.t(:biodiversity_heritage_library)
  %p= I18n.t(:literature_bhl_information)
  %p= link_to I18n.t(:literature_bhl_link), "http://www.biodiversitylibrary.org/name/#{@taxon_concept.entry.title_canonical}", rel: :nofollow

app/views/taxa/literature/_literature_menu.html.haml
#tabs_sidebar
  %ul.tabs
    %li{class: resource_is_active('show')}
      = link_to I18n.t(:literature_references), taxon_literature_path(@taxon_page)
    %li{class: resource_is_active('bhl') || resource_is_active('literature/bhl_title') }
      = link_to I18n.t(:biodiversity_heritage_library), bhl_taxon_literature_path(@taxon_page)
    - unless @literature_links_contents.blank?
      %li{class: resource_is_active('literature_links')}
        = link_to I18n.t(:literature_links_link), literature_links_taxon_literature_path(@taxon_page)

app/views/taxa/literature/bhl.html.haml
- content_for :social_sharing do
  = render 'shared/social_sharing'
#taxon_literature
  = render 'literature_menu'
  .main_container
    .copy
      = render 'bhl_header'
      .heading
        - if @bhl_results && @bhl_results[:total] > 0
          = form_for(@taxon_concept, url: bhl_taxon_literature_path(@taxon_concept), html: { method: "get", class: "select_submit" }) do |f|
            %fieldset
              = label_tag :sort_by, I18n.t(:sort_by_label)
              = select_tag :sort_by, options_for_select([ [ I18n.t(:sort_by_title_ascending), 'title' ], [ I18n.t(:sort_by_title_descending), 'title_desc' ],
                [ I18n.t(:sort_by_year_ascending), 'year' ], [ I18n.t(:sort_by_year_descending), 'year_desc' ] ], @sort)
            %fieldset.actions
              = submit_tag I18n.t(:sort_by_button), name: nil
      - if @bhl_results && @bhl_results[:total] > 0
        = will_paginate @bhl_results[:results], previous_label: I18n.t(:pagination_previous), next_label: I18n.t(:pagination_next),
          inner_window: 2, outer_window: 2
        %table.standard
          %thead
            %tr
              %th= I18n.t(:title)
              %th= I18n.t(:year)
              %th= I18n.t(:details_title)
              %th= I18n.t(:pages_title)
          %tbody
            - @bhl_results[:results].each do |r|
              - if @selected_hierarchy_entry
                - item_link = entry_bhl_title_path(@taxon_concept, @selected_hierarchy_entry, r['title_item_id'])
              - else
                - item_link = bhl_title_path(@taxon_concept, r['title_item_id'])
              %tr
                %td
                  = link_to([r['publication_title'], r['volume_info']].join(' ; '), item_link)
                %td
                  = r['year']
                %td
                  = r['details']
                %td.nowrap
                  = link_to(I18n.t(:pages_with_count, count: r['numFound']), item_link)
        = will_paginate @bhl_results[:results], previous_label: I18n.t(:pagination_previous), next_label: I18n.t(:pagination_next),
          inner_window: 2, outer_window: 2
      - else
        .empty
          %p= I18n.t(:literature_empty)

app/views/taxa/literature/bhl_title.html.haml
- content_for :social_sharing do
  = render 'shared/social_sharing'
#taxon_literature
  = render 'literature_menu'
  .main_container
    .copy
      = render 'bhl_header'
      - if @bhl_title_results && @bhl_title_results[:total] > 0
        %table.standard
          %thead
            %tr
              %th= I18n.t(:title)
              %th= I18n.t(:year)
              %th= I18n.t(:details_title)
              %th= I18n.t(:pages_title)
          %tbody
            %tr
              %td
                - first_result = @bhl_title_results[:results].first
                = external_link_to([first_result['publication_title'], first_result['volume_info']].join(' ; '), "http://www.biodiversitylibrary.org/item/#{first_result['title_item_id']}", rel: :nofollow)
              %td
                = first_result['year']
              %td
                = first_result['details']
              %td.nowrap
                = I18n.t(:pages_with_count, count: @bhl_title_results[:total])
            - @bhl_title_results[:results].each do |r|
              %tr
                %td
                  - link_text = [r['prefix'], r['number']].join(' ')
                  - link_text = I18n.t(:text_capital) if link_text.strip.blank?
                  = external_link_to(link_text, "http://www.biodiversitylibrary.org/page/#{r['id']}", rel: :nofollow)
                %td
                %td
                %td

app/views/taxa/literature/literature_links.html.haml
- content_for :social_sharing do
  = render 'shared/social_sharing'
#taxon_literature
  = render 'literature_menu'
  #taxon_detail
    #main.main_container
      %h3= I18n.t(:literature_links)
      .section
        - unless @literature_links_contents.blank?
          = render 'taxa/resources/link_objects', { content: @literature_links_contents }

app/views/taxa/literature/show.html.haml
- content_for :social_sharing do
  = render 'shared/social_sharing'
#taxon_literature
  = render 'literature_menu'
  .main_container
    .copy
      - unless @references.blank?
        %p.help_text= I18n.t(:the_following_bibliography)
      %h3= I18n.t(:literature_header)
      - if @references.blank?
        .empty
          %p= I18n.t(:literature_empty)
      - else
        %ul.ref_list
          - @references.each do |ref|
            = render "refs/show_as_list_item", { ref: ref }