config/routes.rb
# first created -> highest priority.
Eol::Application.routes.draw do

  # Root should be first, since it's most frequently used and should return quickly:
  root :to => 'content#index'
  
  #resque
  mount Resque::Server.new, at: "/resque"
  # Permanent redirects. Position them before any routes they take precedence over.
  match '/podcast' => redirect('http://podcast.eol.org/podcast')
  match '/pages/:taxon_id/curators' => redirect("/pages/%{taxon_id}/community/curators")
  match '/pages/:taxon_id/images' => redirect("/pages/%{taxon_id}/media")
  match '/pages/:taxon_id/classification_attribution' => redirect("/pages/%{taxon_id}/names")
  match '/pages/:taxon_id/entries/:entry_id' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/overview")
  match '/pages/:taxon_id/entries/:entry_id/overview' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/overview")
  match '/pages/:taxon_id/entries/:entry_id/details' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/details")
  match '/pages/:taxon_id/classification_attribution' => redirect("/pages/%{taxon_id}/names")
  match '/pages/:taxon_id/community' => redirect("/pages/%{taxon_id}/communities")
  match '/pages/:taxon_id/community/collections' => redirect("/pages/%{taxon_id}/communities/collections")
  match '/pages/:taxon_id/community/curators' => redirect("/pages/%{taxon_id}/communities/curators")
  match '/pages/:taxon_id/hierarchy_entries/:entry_id/community' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/communities")
  match '/pages/:taxon_id/hierarchy_entries/:entry_id/community/collections' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/communities/collections")
  match '/pages/:taxon_id/hierarchy_entries/:entry_id/community/curators' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/communities/curators")
  match '/taxa/content/:taxon_id' => redirect("/pages/%{taxon_id}/details")
  match '/taxa/images/:taxon_id' => redirect("/pages/%{taxon_id}/media")
  match '/taxa/maps/:taxon_id' => redirect("/pages/%{taxon_id}/maps")
  match '/settings' => redirect("/")
  match '/account/show/:user_id' => redirect("/users/%{user_id}")
  match '/users/forgot_password' => redirect("/users/recover_account")
  match '/users/:user_id/reset_password/:recover_account_token' => redirect("/users/recover_account")
  match '/info/xrayvision' => redirect("/collections/14770")
  match '/info/brian-skerry' => redirect("/collections/29285")
  match '/info/naturesbest2011' => redirect("/collections/19338")
  match '/info/naturesbest2012' => redirect("/collections/54659")
  match '/info/naturesbest2013' => redirect("/collections/103870")
  match '/voc/table_of_contents' => redirect("/schema/eol_info_items.xml")
  match '/voc/table_of_contents#:term' => redirect("/schema/eol_info_items.xml%{term}")
  match '/index' => redirect('/')
  match '/home.html' => redirect('/')
  match '/favicon' => redirect('/assets/favicon.ico')
  match '/forum' => redirect('/forums'), :as => 'forum_redirect'
  match '/schema/terms/:id' => 'schema#terms', :as => 'schema_terms'

  # Taxa nested resources with pages as alias... this is quite large, sorry. Please keep it high in the routes file,
  # since it's 90% of the website.  :)
  resources :pages, :only => [:show], :controller => 'taxa', :as => 'taxa' do
    resource :overview, :only => [:show], :controller => 'taxa/overview'
    resource :tree, :only => [:show], :controller => 'taxa/trees'
    resources :maps, :only => [:index], :controller => 'taxa/maps'
    resources :media, :only => [:show], :controller => 'taxa/media'
    resources :details, :except => [:show], :controller => 'taxa/details'
    resource :worklist, :only => [:show], :controller => 'taxa/worklist'
    resources :data_objects, :only => [:create, :new]
    resource :taxon_concept_reindexing, :as => 'reindexing', :only => [:create],
      :controller => 'taxa/taxon_concept_reindexing'
    resources :data, :only => [:index], :controller => 'taxa/data' do
      collection do
        get 'about'
        get 'glossary'
        get 'ranges'
      end
    end
    resources :hierarchy_entries, :as => 'entries', :only => [:show] do
      member do
        put 'switch'
      end
      resource :overview, :only => [:show], :controller => 'taxa/overview'
      resource :tree, :only => [:show], :controller => 'taxa/trees'
      resources :maps, :only => [:index], :controller => 'taxa/maps'
      resources :media, :only => [:index], :controller => 'taxa/media'
      resources :details, :only => [:index], :controller => 'taxa/details'
      resources :data, :only => [:index], :controller => 'taxa/data' do
        collection do
          get 'about'
          get 'glossary'
          get 'ranges'
        end
      end
      resources :communities, :only => [:index], :controller => 'taxa/communities' do
        collection do
          get 'collections'
          get 'curators'
        end
      end
      resources :names, :only => [:index, :create, :update], :controller => 'taxa/names' do
        collection do
          get 'common_names'
          get 'related_names'
          get 'synonyms'
          get 'delete'
        end
        member do
          get 'vet_common_name'
        end
      end
      resource :literature, :only => [:show], :controller => 'taxa/literature' do
        collection do
          get 'bhl'
          get 'literature_links'
        end
      end
      resources :resources, :only => [:index], :controller => 'taxa/resources' do
        collection do
          get 'partner_links'
          get 'identification_resources'
          get 'education'
          get 'nucleotide_sequences'
          get 'biomedical_terms'
          get 'citizen_science'
          get 'news_and_event_links'
          get 'related_organizations'
          get 'multimedia_links'
        end
      end
      resources :updates, :only => [:index], :controller => 'taxa/updates' do
        collection do
          get 'statistics'
        end
      end
    end
    resources :media, :only => [:index], :controller => 'taxa/media'
    resources :names, :only => [:index, :create, :update], :controller => 'taxa/names' do
      collection do
        get 'common_names'
        get 'related_names'
        get 'synonyms'
        get 'delete'
      end
      member do
        get 'vet_common_name'
      end
    end
    resource :literature, :only => [:show], :controller => 'taxa/literature' do
      collection do
        get 'bhl'
        get 'literature_links'
      end
    end
    resources :resources, :controller => 'taxa/resources', :only => [:index] do
      collection do
        get 'partner_links'
        get 'identification_resources'
        get 'education'
        get 'nucleotide_sequences'
        get 'biomedical_terms'
        get 'citizen_science'
        get 'news_and_event_links'
        get 'related_organizations'
        get 'multimedia_links'
      end
    end
    resources :communities, :only => [:index], :controller => 'taxa/communities' do
      collection do
        get 'collections'
        get 'curators'
      end
    end
    resources :updates, :only => [:index], :controller => 'taxa/updates' do
      collection do
        get 'statistics'
      end
    end
  end

  # Communities nested resources
  # TODO - these member methods want to be :put. Capybara always uses :get, so in the interests of simple tests:
  resources :communities, :except => [:index] do
    collection do
      get 'choose'
      put 'make_editors'
    end
    member do
      get 'join'
      get 'leave'
      get 'delete'
      put 'make_editor'
      get 'revoke_editor'
    end
    resource :newsfeed, :only => [:show], :controller => 'communities/newsfeeds'
    resources :collections, :controller => 'communities/collections'
    resources :members do
      member do
        # TODO - these shouldn't be GETs, but I really want them to be links, not forms, sooooo...
        get 'grant_manager'
        get 'revoke_manager'
      end
    end
  end

  resources :collections do
    member do
      get 'choose'
      get 'reindex'
    end
    collection do
      get 'get_name'
      get 'get_uri_name'
      get 'cache_inaturalist_projects'
      get 'choose_collect_target'
      get 'choose_editor_target'
      get 'choose_taxa_data'
      post 'collect_item'
      post 'download_taxa_data'
    end
    resource :newsfeed, :only => [:show], :controller => 'collections/newsfeeds'
    resources :editors, :only => [:index], :controller => 'collections/editors'
    resource :inaturalist, :only => [:show], :controller => 'collections/inaturalists'
  end

  resources :collection_jobs, :only => [:create]

  resources :content_partners do
    member do
      post 'new'
    end
    resources :content_partner_contacts, :as => 'contacts', :except => [:index, :show], :controller => 'content_partners/content_partner_contacts' do
      member do
        delete 'delete'
      end
    end
    resources :content_partner_agreements, :as => 'agreements', :except => [:index, :destroy],
      :controller => 'content_partners/content_partner_agreements'
    resource :statistics, :only => [:show], :controller => 'content_partners/statistics'
    resources :resources, :controller => 'content_partners/resources' do
      member do
        get 'force_harvest', :controller => 'content_partners/resources'
        post 'force_harvest', :controller => 'content_partners/resources'
      end
      resources :harvest_events, :only => [:index, :update], :controller => 'content_partners/resources/harvest_events'
      resources :hierarchies, controller: 'content_partners/resources/hierarchies', only: [:edit, :update]  do
        member do
          post 'request_publish', :controller => 'content_partners/resources/hierarchies'
        end
      end
    end
  end

  resources :users, :path_names => { :new => :register } do
    member do
      get 'terms_agreement'
      post 'terms_agreement'

app/models/notifier.rb
class Notifier < ActionMailer::Base

  helper :application, :taxa

  def curator_approved(user)
    @user = user
    mail(
      subject: I18n.t(:subject, curator_level: user.curator_level.translated_label, scope: [:notifier, :curator_approved]),
      to: user.email,
      from: $SPECIES_PAGES_GROUP_EMAIL_ADDRESS )
  end

  def contact_us_auto_response(contact)
    @contact = contact
    contact_subject = ContactSubject.find(contact.contact_subject_id)
    mail(
      subject: I18n.t(:subject, title: contact_subject.title, scope: [:notifier, :contact_us_auto_response]),
      to: contact.email,
      from: $NO_REPLY_EMAIL_ADDRESS )
  end

  def contact_us_message(contact)
    @contact = contact
    contact_subject = ContactSubject.find(contact.contact_subject_id)
    contact_recipients = contact_subject.recipients
    contact_recipients = contact_recipients.split(',').map { |c| c.strip }

    mail(
      subject: I18n.t(:subject, title: contact_subject.title, scope: [:notifier, :contact_us_message]),
      to: contact_recipients,
      from: contact.email )
  end

  def content_partner_statistics_reminder(content_partner, content_partner_contact, month, year)
    @content_partner = content_partner
    @content_partner_contact = content_partner_contact
    @month = month
    @year = year
    mail(
      subject: I18n.t(:subject, partner_full_name: content_partner.full_name, month: month,
                                   year: year, scope: [:notifier, :content_partner_statistics_reminder]),
      to: content_partner_contact.email,
      from: $SPECIES_PAGES_GROUP_EMAIL_ADDRESS )
  end

  def content_partner_created(partner, user)
    @partner = partner
    @user = user
    mail(
      subject: I18n.t(:subject, partner_full_name: partner.full_name, user_full_name: user.full_name,
                           scope: [:notifier, :content_partner_created]),
      to: $SPECIES_PAGES_GROUP_EMAIL_ADDRESS,
      from: $NO_REPLY_EMAIL_ADDRESS )
  end

  def content_partner_resource_created(partner, resource, user)
    @partner = partner
    @resource = resource
    @user = user
    mail(
      subject: I18n.t(:subject, partner_full_name: partner.full_name, resource_title: resource.title,
                           user_full_name: user.full_name, scope: [:notifier, :content_partner_resource_created]),
      to: $SPECIES_PAGES_GROUP_EMAIL_ADDRESS,
      from: $NO_REPLY_EMAIL_ADDRESS )
  end

  def content_partner_resource_force_harvest_request(partner, resource, user)
    @partner = partner
    @resource = resource
    @user = user
    mail(
      subject: I18n.t(:subject, partner_full_name: partner.full_name, resource_title: resource.title,
                           user_full_name: user.full_name, scope: [:notifier, :content_partner_resource_force_harvest_request]),
      to: $SPECIES_PAGES_GROUP_EMAIL_ADDRESS,
      from: $NO_REPLY_EMAIL_ADDRESS )
  end

  def content_partner_resource_hierarchy_publish_request(partner, resource, hierarchy, user)
    @partner = partner
    @resource = resource
    @hierarchy = hierarchy
    @user = user
    mail(
      subject: I18n.t(:subject, partner_full_name: partner.full_name, resource_title: resource.title,
                           user_full_name: user.full_name, scope: [:notifier, :content_partner_resource_hierarchy_publish_request]),
      to: $SPECIES_PAGES_GROUP_EMAIL_ADDRESS,
      from: $NO_REPLY_EMAIL_ADDRESS )
  end

  # TODO: ContentPartnerContact does not have language preference so we can't I18nise this email
  # TODO: What about sending to content partner owner, (WEB-2806)?
  def activity_on_content_partner_content(content_partner, content_partner_contact, activity)
    recipient = set_recipient(content_partner_contact.email)
    unless recipient.blank?
      @content_partner = content_partner
      @content_partner_contact = content_partner_contact
      @activity = activity
      mail(
        subject: I18n.t(:subject, partner_full_name: content_partner.full_name,
                           scope: [:notifier, :activity_on_content_partner_content]),
        to: recipient,
        from: $SPECIES_PAGES_GROUP_EMAIL_ADDRESS )
    end
  end

  # TODO: Since this is a system sent message we should probably be passing the recipient language preference into the I18n strings that make up this message.
  def activity_on_user_content(user, activity)
    recipient = set_recipient(user.email)
    unless recipient.blank?
      @user = user
      @activity = activity
      mail(
        subject: I18n.t(:subject, scope: [:notifier, :activity_on_user_content]),
        to: recipient,
        from: $SPECIES_PAGES_GROUP_EMAIL_ADDRESS )
    end
  end

  def user_activated(user)
    @user = user
    mail(
      subject: I18n.t(:subject, scope: [:notifier, :user_activated]),
      to: user.email,
      from: $NO_REPLY_EMAIL_ADDRESS )
  end

  def user_activated_with_open_authentication(user, translated_oauth_provider)
    @user = user
    @translated_oauth_provider = translated_oauth_provider
    mail(
      subject: I18n.t(:subject, scope: [:notifier, :user_activated_with_open_authentication]),
      to: user.email,
      from: $NO_REPLY_EMAIL_ADDRESS )
  end

  def user_recover_account(user, temporary_login_url)
    @user = user
    @temporary_login_url = temporary_login_url
    mail(
      subject: I18n.t(:subject, scope: [:notifier, :user_recover_account]),
      to: user.email,
      from: $NO_REPLY_EMAIL_ADDRESS )
  end

  def user_verification(user, url)
    @user = user
    @verify_user_url = url
    mail(
      subject: I18n.t(:subject, scope: [:notifier, :user_verification]),
      to: user.email,
      from: $NO_REPLY_EMAIL_ADDRESS )
  end

  def user_message(name, email, message)
    @name = name
    @message = message
    mail(
      subject: I18n.t(:subject, scope: [:notifier, :user_message]),
      to: email,
      cc: $SPECIES_PAGES_GROUP_EMAIL_ADDRESS,
      from: $NO_REPLY_EMAIL_ADDRESS )
  end

  def unsubscribed_to_notifications(user)
    @user = user
    mail(
      subject: I18n.t(:subject, scope: [:notifier, :unsubscribed_to_notifications]),
      to: user.email,
      from: $NO_REPLY_EMAIL_ADDRESS )
  end

private
  def set_recipient(email_address)
    # Override recipient if site is configured to send all reports to a single email address
    # TODO: Maybe change this config parameter name, why would we be emailing all reports to a curator?
    # TODO: Cache this parameter, so we don't get SQL call every time?
    parameter = EolConfig.email_actions_to_curators_address
    if parameter
      parameter.value
    else
      email_address
    end
  end
end

app/views/notifier/_comments.text.haml
- if comments.blank?
  = I18n.t(:comments_empty, :scope => :notifier)
- else
  - comments.each do |comment|
    - next if comment.parent.nil?
    - commented_on_name = comment.parent.summary_name
    - commented_on_url = nil
    - case comment.parent_type
    - when 'TaxonConcept'
      - commented_on_url = taxon_overview_url(comment.parent, :host => EOL::Server.domain)
    - when 'DataObject'
      - commented_on_url = data_object_url(comment.parent, :host => EOL::Server.domain)
    = I18n.t(:user_commented_on_something_date_body, :users_name => h(comment.user.full_name),
      :users_url => user_url(comment.user, :host => EOL::Server.domain),
      :curator_level => (comment.user.curator_level.translated_label rescue 'User'),
      :commented_on_name => commented_on_name, :commented_on_url => commented_on_url,
      :comment_body => strip_tags(comment.body), :comment_date => format_date_time(comment.created_at),
      :scope => :notifier)

app/views/notifier/_curator_activity_log.text.haml
- if actions.blank?
  = I18n.t(:activity_log_empty, :scope => :notifier)
- else
  - actions.each do |action|
    - users_name = h strip_tags(action.user.full_name)
    - users_url = user_url(action.user, :host => EOL::Server.domain)
    - users_curator_level = action.user.curator_level.translated_label rescue 'User'
    - action_date = format_date_time(action.created_at)
    - # We check to make sure the action.data_object association is 'real' i.e. curator_activity_logs.target_id == data_objects.id
    - # Consequently this does not handle activity on e.g. ChangeableObjectType.taxon_concept_name (please remove these comments if that changes)
    - if ChangeableObjectType.data_object_scope.include?(action.changeable_object_type_id) && !action.data_object.blank?
      - en_activity_name = nil
      - # Only dealing with a few activities here, if you add more you'll need to change this
      - case action.activity_id
      - when Activity.trusted.id
        - en_activity_name = 'trusted'
      - when Activity.untrusted.id
        - en_activity_name = 'untrusted'
      - when Activity.inappropriate.id
        - en_activity_name = 'inappropriate'
      - when Activity.add_association.id
        - en_activity_name = 'added_association'
      - when Activity.remove_association.id
        - en_activity_name = 'removed_association'
      - unless en_activity_name.nil?
        - object_name = h strip_tags(action.data_object.summary_name)
        - object_url = data_object_url(action.data_object, :host => EOL::Server.domain)
        - taxon_name = nil
        - if en_activity_name == 'trusted' || en_activity_name == 'untrusted'
          - # TODO: This switch is a bandaid and should probably be moved to the CAL model and the methods there for getting taxon/hierarchy entry fixed.
          - # TODO: Not sure if we need extra checks for unpublished/superceded taxon concepts?
          - case action.changeable_object_type_id
          - when ChangeableObjectType.users_data_object.id
            - taxon_concept = action.data_object.users_data_object.taxon_concept rescue nil
            - taxon_name = taxon_concept.title_canonical rescue nil
            - taxon_url = taxon_url(taxon_concept, :host => EOL::Server.domain) rescue ''
          - when ChangeableObjectType.data_object.id
            - # For legacy trust/untrust actions on data_object I don't think we have an associated hierarchy entry, for new actions the COT should be data_objects_hierarchy_entry
            - taxon_name = nil
          - when ChangeableObjectType.data_objects_hierarchy_entry.id
            - taxon_name = action.hierarchy_entry.name.string rescue nil
            - taxon_url = taxon_entry_url(action.hierarchy_entry.taxon_concept, action.hierarchy_entry, :host => EOL::Server.domain) rescue ''
          - when ChangeableObjectType.curated_data_objects_hierarchy_entry.id
            - taxon_name = action.hierarchy_entry.name.string rescue nil
            - taxon_url = taxon_entry_url(action.hierarchy_entry.taxon_concept, action.hierarchy_entry, :host => EOL::Server.domain) rescue ''
        - if taxon_name.nil?
          - if en_activity_name == 'added_association' || en_activity_name == 'removed_association'
            = I18n.t("activity_user_#{en_activity_name}_on_date", :users_name => users_name, :users_url => users_url, :object_name => object_name, :object_url => object_url, :action_date => action_date, :scope => :notifier, :curator_level => users_curator_level)
          - else
            = I18n.t("activity_user_marked_data_object_as_#{en_activity_name}_on_date", :users_name => users_name, :users_url => users_url, :object_name => object_name, :object_url => object_url, :action_date => action_date, :scope => :notifier, :curator_level => users_curator_level)
        - else
          - if en_activity_name == 'added_association' || en_activity_name == 'removed_association'
            = I18n.t("activity_user_#{en_activity_name}_for_taxon_on_date", :users_name => users_name, :users_url => users_url, :object_name => object_name, :object_url => object_url, :taxon_name => strip_tags(taxon_name), :taxon_url => taxon_url, :action_date => action_date, :scope => :notifier, :curator_level => users_curator_level)
          - else
            = I18n.t("activity_user_marked_data_object_as_#{en_activity_name}_for_taxon_on_date", :users_name => users_name, :users_url => users_url, :object_name => object_name, :object_url => object_url, :taxon_name => strip_tags(taxon_name), :taxon_url => taxon_url, :action_date => action_date, :scope => :notifier, :curator_level => users_curator_level)

app/views/notifier/activity_on_content_partner_content.text.haml
= I18n.t(:greeting_dear_name_with_comma, :name => @content_partner_contact.full_name, :species_pages_group_email => $SPECIES_PAGES_GROUP_EMAIL_ADDRESS, :scope => :notifier)
:plain
= t('.message', :partner_full_name => @content_partner.full_name,
  :species_pages_group_email => $SPECIES_PAGES_GROUP_EMAIL_ADDRESS,
  :partner_profile_url => content_partner_url(@content_partner, :host => EOL::Server.domain),
  :curator_activity_log => render('curator_activity_log', {:actions => @activity[:actions]}),
  :data_object_comments =>  render('comments', {:comments => @activity[:object_comments]}),
  :page_comments =>  render('comments', {:comments => @activity[:page_comments]}))
:plain
= I18n.t(:signature_with_species_pages_group_contact, :species_pages_group_email => $SPECIES_PAGES_GROUP_EMAIL_ADDRESS,
  :scope => :notifier)

app/views/notifier/activity_on_user_content.text.haml
= I18n.t(:greeting_dear_name_with_comma, :name => @user.full_name, :species_pages_group_email => $SPECIES_PAGES_GROUP_EMAIL_ADDRESS, :scope => :notifier)
:plain
= t('.message', :members_username => @user.username,
  :species_pages_group_email => $SPECIES_PAGES_GROUP_EMAIL_ADDRESS,
  :curator_activity_log => render('curator_activity_log', {:actions => @activity[:actions]}),
  :data_object_comments =>  render('comments', {:comments => @activity[:object_comments]}),
  :page_comments =>  render('comments', {:comments => @activity[:page_comments]}))
:plain
= I18n.t(:signature_with_species_pages_group_contact, :species_pages_group_email => $SPECIES_PAGES_GROUP_EMAIL_ADDRESS,
  :scope => :notifier)

app/views/notifier/contact_us_auto_response.text.haml
= I18n.t(:greeting_dear_name_with_comma, :name => @contact.name, :scope => :notifier)
:plain
= t('.message')
:plain
= I18n.t(:signature_basic, :scope => :notifier)

app/views/notifier/contact_us_message.text.haml
= t('.message', :from_name => @contact.name, :from_email => @contact.email,
  :subject => @contact.contact_subject.title, :taxon_group => @contact.taxon_group, :message => @contact.comments)

app/views/notifier/content_partner_resource_created.text.haml
= t('.message', :user_full_name => @user.full_name,
  :user_email => @user.email,
  :user_profile_url => user_url(@user, :host => EOL::Server.domain),
  :partner_full_name => @partner.full_name,
  :partner_resources_url => content_partner_resources_url(@partner, :host => EOL::Server.domain),
  :resource_title => @resource.title,
  :resource_url => content_partner_resource_url(@partner, @resource, :host => EOL::Server.domain),
  :resource_created_at_date => @resource.created_at,
  :resource_status => @resource.status_label)

app/views/notifier/content_partner_resource_hierarchy_publish_request.text.haml
= t('.message', :user_full_name => @user.full_name,
  :user_email => @user.email,
  :user_profile_url => user_url(@user, :host => EOL::Server.domain),
  :partner_full_name => @partner.full_name,
  :partner_resources_url => content_partner_resources_url(@partner, :host => EOL::Server.domain),
  :resource_title => @resource.title,
  :resource_url => content_partner_resource_url(@partner, @resource, :host => EOL::Server.domain),
  :hierarchy_edit_url => edit_content_partner_resource_hierarchy_url(@partner, @resource, @hierarchy, :host =>
  EOL::Server.domain))

app/views/notifier/curator_approved.text.haml
= I18n.t(:greeting_dear_name_with_comma, :name => @user.full_name, :scope => :notifier)
:plain
= t('.message', :curator_level => @user.curator_level.translated_label)
:plain
= I18n.t(:signature_with_contact_us_link, :url => contact_us_url(:host => EOL::Server.domain), :scope => :notifier)

app/views/notifier/unsubscribed_to_notifications.text.haml
= I18n.t(:greeting_dear_name_with_comma, :name => @user.full_name, :scope => :notifier)
:plain
= t('.message', :email_prefs_url => edit_user_notification_url(@user, :host => EOL::Server.domain))
:plain
= I18n.t(:signature_with_contact_us_link, :url => contact_us_url(:host => EOL::Server.domain), :scope => :notifier)

app/views/notifier/user_activated.text.haml
= I18n.t(:greeting_dear_name_with_comma, :name => @user.full_name, :scope => :notifier)
:plain
= t('.message', :username => @user.username, :profile_url => user_url(@user, :host => EOL::Server.domain))
:plain
= I18n.t(:signature_with_contact_us_link, :url => contact_us_url(:host => EOL::Server.domain), :scope => :notifier)

app/views/notifier/user_message.text.haml
= I18n.t(:greeting_dear_name_with_comma, :name => @name, :scope => :notifier)
:plain
= @message
:plain
= I18n.t(:signature_basic, :scope => :notifier)

app/views/notifier/user_reset_password.text.haml
= I18n.t(:greeting_dear_name_with_comma, :name => @user.full_name, :scope => :notifier)
:plain
= t('.message', :password_reset_url => @password_reset_url)
:plain
= I18n.t(:signature_with_contact_us_link, :url => contact_us_url(:host => EOL::Server.domain), :scope => :notifier)

app/views/notifier/user_verification.text.haml
= I18n.t(:greeting_dear_name_with_comma, :name => @user.full_name, :scope => :notifier)
:plain
= t('.message', :verification_url => @verify_user_url)
:plain
= I18n.t(:signature_with_contact_us_link, :url => contact_us_url(:host => EOL::Server.domain), :scope => :notifier)