config/routes.rb
# first created -> highest priority.
Eol::Application.routes.draw do

  # Root should be first, since it's most frequently used and should return quickly:
  root :to => 'content#index'
  
  #resque
  mount Resque::Server.new, at: "/resque"
  # Permanent redirects. Position them before any routes they take precedence over.
  match '/podcast' => redirect('http://podcast.eol.org/podcast')
  match '/pages/:taxon_id/curators' => redirect("/pages/%{taxon_id}/community/curators")
  match '/pages/:taxon_id/images' => redirect("/pages/%{taxon_id}/media")
  match '/pages/:taxon_id/classification_attribution' => redirect("/pages/%{taxon_id}/names")
  match '/pages/:taxon_id/entries/:entry_id' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/overview")
  match '/pages/:taxon_id/entries/:entry_id/overview' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/overview")
  match '/pages/:taxon_id/entries/:entry_id/details' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/details")
  match '/pages/:taxon_id/classification_attribution' => redirect("/pages/%{taxon_id}/names")
  match '/pages/:taxon_id/community' => redirect("/pages/%{taxon_id}/communities")
  match '/pages/:taxon_id/community/collections' => redirect("/pages/%{taxon_id}/communities/collections")
  match '/pages/:taxon_id/community/curators' => redirect("/pages/%{taxon_id}/communities/curators")
  match '/pages/:taxon_id/hierarchy_entries/:entry_id/community' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/communities")
  match '/pages/:taxon_id/hierarchy_entries/:entry_id/community/collections' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/communities/collections")
  match '/pages/:taxon_id/hierarchy_entries/:entry_id/community/curators' => redirect("/pages/%{taxon_id}/hierarchy_entries/%{entry_id}/communities/curators")
  match '/taxa/content/:taxon_id' => redirect("/pages/%{taxon_id}/details")
  match '/taxa/images/:taxon_id' => redirect("/pages/%{taxon_id}/media")
  match '/taxa/maps/:taxon_id' => redirect("/pages/%{taxon_id}/maps")
  match '/settings' => redirect("/")
  match '/account/show/:user_id' => redirect("/users/%{user_id}")
  match '/users/forgot_password' => redirect("/users/recover_account")
  match '/users/:user_id/reset_password/:recover_account_token' => redirect("/users/recover_account")
  match '/info/xrayvision' => redirect("/collections/14770")
  match '/info/brian-skerry' => redirect("/collections/29285")
  match '/info/naturesbest2011' => redirect("/collections/19338")
  match '/info/naturesbest2012' => redirect("/collections/54659")
  match '/info/naturesbest2013' => redirect("/collections/103870")
  match '/voc/table_of_contents' => redirect("/schema/eol_info_items.xml")
  match '/voc/table_of_contents#:term' => redirect("/schema/eol_info_items.xml%{term}")
  match '/index' => redirect('/')
  match '/home.html' => redirect('/')
  match '/favicon' => redirect('/assets/favicon.ico')
  match '/forum' => redirect('/forums'), :as => 'forum_redirect'
  match '/schema/terms/:id' => 'schema#terms', :as => 'schema_terms'

  # Taxa nested resources with pages as alias... this is quite large, sorry. Please keep it high in the routes file,
  # since it's 90% of the website.  :)
  resources :pages, :only => [:show], :controller => 'taxa', :as => 'taxa' do
    resource :overview, :only => [:show], :controller => 'taxa/overview'
    resource :tree, :only => [:show], :controller => 'taxa/trees'
    resources :maps, :only => [:index], :controller => 'taxa/maps'
    resources :media, :only => [:show], :controller => 'taxa/media'
    resources :details, :except => [:show], :controller => 'taxa/details'
    resource :worklist, :only => [:show], :controller => 'taxa/worklist'
    resources :data_objects, :only => [:create, :new]
    resource :taxon_concept_reindexing, :as => 'reindexing', :only => [:create],
      :controller => 'taxa/taxon_concept_reindexing'
    resources :data, :only => [:index], :controller => 'taxa/data' do
      collection do
        get 'about'
        get 'glossary'
        get 'ranges'
      end
    end
    resources :hierarchy_entries, :as => 'entries', :only => [:show] do
      member do
        put 'switch'
      end
      resource :overview, :only => [:show], :controller => 'taxa/overview'
      resource :tree, :only => [:show], :controller => 'taxa/trees'
      resources :maps, :only => [:index], :controller => 'taxa/maps'
      resources :media, :only => [:index], :controller => 'taxa/media'
      resources :details, :only => [:index], :controller => 'taxa/details'
      resources :data, :only => [:index], :controller => 'taxa/data' do
        collection do
          get 'about'
          get 'glossary'
          get 'ranges'
        end
      end
      resources :communities, :only => [:index], :controller => 'taxa/communities' do
        collection do
          get 'collections'
          get 'curators'
        end
      end
      resources :names, :only => [:index, :create, :update], :controller => 'taxa/names' do
        collection do
          get 'common_names'
          get 'related_names'
          get 'synonyms'
          get 'delete'
        end
        member do
          get 'vet_common_name'
        end
      end
      resource :literature, :only => [:show], :controller => 'taxa/literature' do
        collection do
          get 'bhl'
          get 'literature_links'
        end
      end
      resources :resources, :only => [:index], :controller => 'taxa/resources' do
        collection do
          get 'partner_links'
          get 'identification_resources'
          get 'education'
          get 'nucleotide_sequences'
          get 'biomedical_terms'
          get 'citizen_science'
          get 'news_and_event_links'
          get 'related_organizations'
          get 'multimedia_links'
        end
      end
      resources :updates, :only => [:index], :controller => 'taxa/updates' do
        collection do
          get 'statistics'
        end
      end
    end
    resources :media, :only => [:index], :controller => 'taxa/media'
    resources :names, :only => [:index, :create, :update], :controller => 'taxa/names' do
      collection do
        get 'common_names'
        get 'related_names'
        get 'synonyms'
        get 'delete'
      end
      member do
        get 'vet_common_name'
      end
    end
    resource :literature, :only => [:show], :controller => 'taxa/literature' do
      collection do
        get 'bhl'
        get 'literature_links'
      end
    end
    resources :resources, :controller => 'taxa/resources', :only => [:index] do
      collection do
        get 'partner_links'
        get 'identification_resources'
        get 'education'
        get 'nucleotide_sequences'
        get 'biomedical_terms'
        get 'citizen_science'
        get 'news_and_event_links'
        get 'related_organizations'
        get 'multimedia_links'
      end
    end
    resources :communities, :only => [:index], :controller => 'taxa/communities' do
      collection do
        get 'collections'
        get 'curators'
      end
    end
    resources :updates, :only => [:index], :controller => 'taxa/updates' do
      collection do
        get 'statistics'
      end
    end
  end

  # Communities nested resources
  # TODO - these member methods want to be :put. Capybara always uses :get, so in the interests of simple tests:
  resources :communities, :except => [:index] do
    collection do
      get 'choose'
      put 'make_editors'
    end
    member do
      get 'join'
      get 'leave'
      get 'delete'
      put 'make_editor'
      get 'revoke_editor'
    end
    resource :newsfeed, :only => [:show], :controller => 'communities/newsfeeds'
    resources :collections, :controller => 'communities/collections'
    resources :members do
      member do
        # TODO - these shouldn't be GETs, but I really want them to be links, not forms, sooooo...
        get 'grant_manager'
        get 'revoke_manager'
      end
    end
  end

  resources :collections do
    member do
      get 'choose'
      get 'reindex'
    end
    collection do
      get 'get_name'
      get 'get_uri_name'
      get 'cache_inaturalist_projects'
      get 'choose_collect_target'
      get 'choose_editor_target'
      get 'choose_taxa_data'
      post 'collect_item'
      post 'download_taxa_data'
    end
    resource :newsfeed, :only => [:show], :controller => 'collections/newsfeeds'
    resources :editors, :only => [:index], :controller => 'collections/editors'
    resource :inaturalist, :only => [:show], :controller => 'collections/inaturalists'
  end

  resources :collection_jobs, :only => [:create]

  resources :content_partners do
    member do
      post 'new'
    end
    resources :content_partner_contacts, :as => 'contacts', :except => [:index, :show], :controller => 'content_partners/content_partner_contacts' do
      member do
        delete 'delete'
      end
    end
    resources :content_partner_agreements, :as => 'agreements', :except => [:index, :destroy],
      :controller => 'content_partners/content_partner_agreements'
    resource :statistics, :only => [:show], :controller => 'content_partners/statistics'
    resources :resources, :controller => 'content_partners/resources' do
      member do
        get 'force_harvest', :controller => 'content_partners/resources'
        post 'force_harvest', :controller => 'content_partners/resources'
      end
      resources :harvest_events, :only => [:index, :update], :controller => 'content_partners/resources/harvest_events'
      resources :hierarchies, controller: 'content_partners/resources/hierarchies', only: [:edit, :update]  do
        member do
          post 'request_publish', :controller => 'content_partners/resources/hierarchies'
        end
      end
    end
  end

  resources :users, :path_names => { :new => :register } do
    member do
      get 'terms_agreement'
      post 'terms_agreement'

app/models/content_partner/as_unassisted.rb
# encoding: utf-8

class ContentPartner
  # Contextual model for self-created content partners
  class AsUnassisted < ActiveType::Record[ContentPartner]
    after_create :notify_master_curators

    private

    def notify_master_curators
      Notifier.content_partner_created(self, user).deliver
    end
  end
end

app/models/content_partner/meta.rb
# encoding: utf-8

class ContentPartner
  # Encapsulates the variables needed to render the show/edit pages.
  class Meta
    def title
      I18n.t(:content_partners_page_title)
    end

    def subtitle
      I18n.t(:content_partner_new_page_subheader)
    end
  end
end

app/controllers/content_partners/content_partner_agreements_controller.rb
class ContentPartners::ContentPartnerAgreementsController < ContentPartnersController

  before_filter :check_authentication

  layout 'partners'

  # GET /content_partners/:content_partner_id/agreements/new
  def new
    @partner = ContentPartner.find(params[:content_partner_id], include: :content_partner_agreements)
    access_denied unless current_user.can_update?(@partner)
    @current_agreement = @partner.agreement
    new_agreement_params = { created_at: 0.seconds.from_now }
    # Content of new agreement is copied from the current agreement, if it exists, otherwise the template is used
    new_agreement_params[:body] = @current_agreement.body unless @current_agreement.blank?
    @agreement = @partner.content_partner_agreements.build(new_agreement_params)
    @page_subheader = I18n.t(:content_partner_agreement_subheader)
  end

  # POST /content_partners/:content_partner_id/agreements
  def create
    @partner = ContentPartner.find(params[:content_partner_id])
    set_params_when_agreeing_to_terms if params[:commit_agree_to_terms]
    @new_agreement = @partner.content_partner_agreements.build(params[:content_partner_agreement])
    access_denied unless current_user.can_create?(@new_agreement)
    if @new_agreement.save
      if params[:commit_agree_to_terms]
        flash[:notice] = I18n.t(:content_partner_agreement_signed_successful_notice)
      else
        flash[:notice] = I18n.t(:content_partner_agreement_create_successful_notice)
      end
      redirect_to content_partner_resources_path(@partner), status: :moved_permanently
    else
      if params[:commit_agree_to_terms]
        flash.now[:error] = I18n.t(:content_partner_agreement_signed_unsuccessful_error)
      else
        flash.now[:error] = I18n.t(:content_partner_agreement_create_unsuccessful_error)
      end
    end
  end

  # GET /content_partners/:content_partner_id/agreements/:id/edit
  def edit
    @partner = ContentPartner.find(params[:content_partner_id], include: :content_partner_agreements)
    @agreement = @partner.content_partner_agreements.find(params[:id])
    access_denied unless current_user.can_update?(@agreement)
    @page_subheader = I18n.t(:content_partner_agreement_subheader)
  end

  # PUT /content_partners/:content_partner_id/agreements/:id
  def update
    @partner = ContentPartner.find(params[:content_partner_id])
    @agreement = @partner.content_partner_agreements.find(params[:id])
    access_denied unless current_user.can_update?(@agreement)
    set_params_when_agreeing_to_terms if params[:commit_agree_to_terms]
    if @agreement.update_attributes(params[:content_partner_agreement])
      if params[:commit_agree_to_terms]
        flash[:notice] = I18n.t(:content_partner_agreement_signed_successful_notice)
      else
        flash[:notice] = I18n.t(:content_partner_agreement_update_successful_notice)
      end
      redirect_to content_partner_resources_path(@partner), status: :moved_permanently
    else
      if params[:commit_agree_to_terms]
        flash.now[:error] = I18n.t(:content_partner_agreement_signed_unsuccessful_error)
      else
        flash.now[:error] = I18n.t(:content_partner_agreement_update_unsuccessful_error)
      end
    end
  end

  # GET /content_partners/:content_partner_id/agreements/:id
  def show
    @partner = ContentPartner.find(params[:content_partner_id], include: :content_partner_agreements)
    @agreement = @partner.content_partner_agreements.find(params[:id])
    access_denied unless current_user.can_read?(@agreement)
    @page_subheader = I18n.t(:content_partner_agreement_subheader)
  end

private

  def set_params_when_agreeing_to_terms
    params[:content_partner_agreement][:signed_on_date] ||= Time.now
    params[:content_partner_agreement][:ip_address] ||= request.remote_ip
    params[:content_partner_agreement][:is_current] ||= true
  end
end

app/controllers/users/content_partners_controller.rb
class Users::ContentPartnersController < UsersController

  skip_before_filter :extend_for_open_authentication

  # GET /users/:user_id/content_partners
  def index
    @user = User.find(params[:user_id], include: [:content_partners])
    redirect_if_user_is_inactive
    preload_user_associations
    @partners = @user.content_partners
    @partners.delete_if{ |cp| !current_user.can_read?(cp) }
    @new_partner = ContentPartner.new(user: @user)
    @rel_canonical_href = user_content_partners_url(@user)
  end

end

app/helpers/content_partners/resources/harvest_events_helper.rb
module ContentPartners::Resources::HarvestEventsHelper
  def event_not_published
    I18n.t(:content_partner_resource_harvest_event_not_published)
  end

  def event_currently_published
    I18n.t(:content_partner_resource_harvest_event_current_published)
  end
  
  def event_previously_published
    I18n.t(:content_partner_resource_harvest_event_previously_published)
  end
end

app/helpers/content_partners/resources_helper.rb
module ContentPartners::ResourcesHelper

    def attribute_or_empty(attribute)
      attribute.blank? ? I18n.t(:value_empty) : attribute
    end

    def time_or_empty(time)
      format_date_time(time, format: :medium) || I18n.t(:value_empty)
    end

    def link_to_url_or_empty(url)
      if url.blank?
        I18n.t(:value_empty)
      else
        link_to url.sub(/^.*\//, ''), url
      end
    end

    def request_to_publish_hierarchy_button(hierarchy)
      button_to(
        I18n.t("helpers.submit.hierarchy.request_publish"),
        request_publish_content_partner_resource_hierarchy_path(
          @partner, @resource, hierarchy
        ),
        data: { confirm:
          I18n.t(:content_partner_resource_hierarchy_confirm_request_publish,
                 hierarchy_label: h(hierarchy.label)) }
      )
    end

    def en_resource_status
      status = @resource.resource_status.try(:label, "en")
      if status
        status.downcase.gsub(" ","_")
      else
        "unknown"
      end
    end
end

app/helpers/content_partners_helper.rb
# Helpers for content patnter views
module ContentPartnersHelper
  def display_content_partners_navigation?
    @partner && @partner.id &&
    (
      (action_name == "show" &&
       controller_name != "content_partner_agreements") ||
      (action_name == "index" && controller_name != "harvest_events")
    )
  end

  def oldest_published_harvest_time(partner)
    I18n.t(:content_partner_latest_published_harvest_event_time_ago,
           time_passed:
           time_ago_in_words(partner.latest_published_harvest_events.
                             first.published_at))
  end

  def latest_published_harvest_time(partner)
    I18n.t(:content_partner_latest_published_harvest_event_time_ago,
           time_passed:
           time_ago_in_words(partner.latest_published_harvest_events.
                             first.published_at))
  end

  def field_name(attribute)
    I18n.t "activerecord.attributes.content_partner_agreement.#{attribute}"
  end

  def field_value(val)
    val.blank? ? I18n.t(:value_empty) : val
  end

  def agreement
    if @partner.agreement.mou_url.blank?
      content_partner_agreement_path(@partner, @partner.agreement)
    else
      @partner.agreement.mou_url
    end 
  end

end

app/views/content_partners/content_partner_agreements/_modify_agreement.html.haml
%dl
  %dt
    = form.label :body
  %dd
    = form.text_area :body
  %dt
    = form.label :mou_url, raw(I18n.t('helpers.label.content_partner_agreement.mou_url'))
    %p= raw(I18n.t('helpers.label.content_partner_agreement.mou_url_more', :upload_content_url => url_for(:controller => 'administrator/content_upload', :action => 'index')))
  %dd
    = form.text_field :mou_url, { :maxlength => 255 }

app/views/content_partners/content_partner_agreements/_sign_agreement.html.haml
= form_for @agreement do |form|
  %fieldset
    = raw @agreement.body
    = form.hidden_field :body, :value => @agreement.body
    = form.hidden_field :created_at, :value => @agreement.created_at
    %dl
      %dt
        = form.label :signed_by
      %dd
        = form.text_field :signed_by, { :maxlength => 255 }
  %fieldset.actions
    = form.submit I18n.t('helpers.submit.content_partner_agreement.agree'), :name => :commit_agree_to_terms
    = link_to I18n.t(:content_partner_agreement_cancel_sign_agreement_link), @partner

app/views/content_partners/content_partner_agreements/_template.html.haml
.agreement
  %h3
    Content partner agreement between the Encyclopedia of Life and
    = partner.full_name

  %p
    Created on
    = agreement.created_at

  %h4
    Introduction
  %p
    The Encyclopedia of Life and
    = partner.full_name
    agree to work together to develop and share critical biodiversity content to aid in
    assembling the Encyclopedia of Life. The Encyclopedia of Life will have access to data
    objects provided by
    = partner.full_name
    and
    = partner.full_name
    will have access to the resources of the Encyclopedia of Life, including species pages,
    scanned literature, and informatics tools in accordance with the terms listed below.

  %h4
    The parties
  %p
    The Encyclopedia of Life (EOL) is an informal consortium of organizations dedicated to
    building an on-line Encyclopedia of Life composed of content-rich multi-media species pages
    for all of the presently known species on Earth. The cornerstone institutions of the EOL are
    listed at http://www.eol.org/info/global_partners. Currently, the EOL is composed of five working groups:

  %dl
    %dt
      Species Pages Group
    %dd
      Defines the composition of information on species pages; works with the scientific community
      to identify potential sources of information (such as the Content Partner) for the species pages
      and to authenticate the information on the species pages; establishes licensing agreements with
      data providers.

    %dt
      Biodiversity Informatics Group
    %dd
      Conceptualizes and prepares the software needed to host and to search the species pages;
      applies taxonomic intelligence to the scientific names on the species pages and in the literature.

    %dt
      Scanning and Digitization Group
    %dd
      Working with the Biodiversity Heritage Library, a consortium of many of the world's largest
      natural history libraries, digitizes and marks up the world's biodiversity literature.

    %dt
      Education and Outreach Group
    %dd
      Exploits the EOL's potential by exploring and promoting its educational uses.

    %dt
      Biodiversity Synthesis Group
    %dd
      Holds synthesis meetings to help reach taxonomic consensus on megadiverse groups; develops tools
      for analyzing and synthesizing information across species pages.

  %h5= partner.full_name
  %p= sanitize partner.description.balance_tags

  %h4
    Content licensing
  %p
    To the greatest extent possible, the Encyclopedia of Life promotes an open-source, open-access approach.
    Therefore, it requires that content providers (including the EOL's core participants) serving information
    through the EOL agree to the following provisions:

  %ol
    %li
      Content providers warrant and represent that the content they provide under this Agreement either
      is in the public domain, that they hold the rights, or that they have obtained the necessary
      permissions from the rights-holders to use, reproduce and disseminate the content for use in the
      Encyclopedia, and that the content providers will hold EOL and the members of the EOL consortium
      harmless in the event of a claim arising from the submitted content.
    %li
      All information currently in the public domain will remain in the public domain. Neither the
      EOL nor the content providers will seek to assert any IPR over any public domain materials that
      are made available through the EOL.
    %li
      Content providers are required to adopt a Creative Commons license for the information subject
      to copyright that they serve through the EOL. The default and preferred license is CC-BY (Attribution),
      which allows users to copy, transmit and reuse the information, and to remix or adapt the information,
      as long as attribution regarding the source of the information is maintained.
    %li
      Content providers who request some restrictions on re-use of their information may select an
      alternate Creative Commons license: CC-BY-SA (Attribution-ShareAlike), CC-BY-NC
      (Attribution-NonCommercial) or CC-BY-NC-SA (Attribution-NonCommercial-ShareAlike).
    %li
      The EOL will provide attribution information for all content that it serves. EOL will also
      indicate the Creative Commons license attached to each object (text, structured data, graphics,
      multimedia, etc.).

  %p
    Full information about the Creative Commons licensing can be found at http://www.creativecommons.org.

  %h4
    Content attribution
  %p
    EOL intends to provide attribution for all provided content in the manner specified by
    = partner.full_name
    \. The methodology EOL uses to attribute the content provided by
    = partner.full_name
    is fundamentally based on multi-level text strings and/or logos at the level of individual data objects.
    = partner.full_name
    will submit attribution information via the Transfer Schema. Note: The specific style and
    techniques employed for display of attribution for data objects may change as the EOL evolves.

  %h4
    Roles and conditions of use
  %p
    In providing its content to EOL,
    = partner.full_name
    will:

  %ul
    %li
      Provide its content via a format and interchange method compatible with the EOL.
    %li
      Provide data objects as-is with no warranty or claim of fitness for purpose.
    %li
      Respond to the originators of comments or feedback communicated to
      = partner.full_name
      via the EOL regarding its content.
    %li
      Work with the EOL to improve the quality of the provided data objects and reduce errors.
    %li
      Comply with the Creative Commons licenses of any EOL content from other Content Partners
      that it may choose to use for its own purposes and to provide full attribution in the
      specified manner of the license.
    %li
      Be able to display the EOL logo on its web site.


  %p
    In handling the content provided by
    = partner.full_name
    , EOL will:

  %ul
    %li
      Provide tools and methods to enable
      = partner.full_name
      to provide its content to the EOL.
    %li
      Cache
      = partner.full_name
      's data objects along with similar content from other sources on EOL's servers.
    %li
      Attribute all of
      = partner.full_name
      's data objects according to its preferred Creative Commons licenses and in the manner specified by
      = partner.full_name
      = "."
    %li
      Present or pass along
      = partner.full_name
      's data objects to others using web services (such as APIs) which will carry the same Creative Commons
      licenses and specified manner of attribution.
    %li
      Refer all requests for re-usage of
      = partner.full_name
      's content to
      = partner.full_name
      = "."
    %li
      Not alter the data objects provided; however EOL will enable annotations or comments to be added.
    %li
      Notify
      = partner.full_name
      of any comments or feedback received about its data objects.
    %li
      Work with
      = partner.full_name
      to improve the quality of the provided data objects and reduce errors.
    %li
      Notify
      = partner.full_name
      of statistics about the usage of its data objects.
    %li
      Enable
      = partner.full_name
      to access content from the EOL and to use that content on
      = partner.full_name
      's own server or site according to the terms of the Creative Commons licenses, if any, for that content.
    %li
      Show
      = partner.full_name
      's logo and project description on its list of data partners.
    %li
      Post on the EOL site a statement designating an agent for receiving notice of any content
      alleged to violate copyright or other rights; remove any content upon receiving such notice or
      upon discovering infringing content.
    %li
      EOL may elect at its sole discretion to present all, portions or none of any data objects
      provided by
      = partner.full_name
      and reserves the right to redact or remove any illegal, offensive, or objectionable content.

  %p
    The parties do not intend to create a legal partnership, principal/agent, or joint venture
    relationship and nothing in this agreement shall be construed as creating such a relationship
    between the parties. Neither party may incur any obligation on behalf of the other.
  %p
    This agreement is non-exclusive, and in no way restricts either EOL or
    = partner.full_name
    from participating in similar activities or arrangements with other public or private initiatives,
    organizations, or individuals.
  %p
    This agreement and the obligations set forth herein shall be subject to available funding and
    nothing in this agreement creates any financial obligation on the part of either party.
  %p
    = partner.full_name
    agrees that it shall not use the names or logos of EOL or any EOL
    cornerstone institution in any manner or through any medium without EOL’s or the EOL cornerstone
    institution’s prior, written consent. Upon the expiration or termination of this Agreement,
    = partner.full_name
    shall immediately cease to use the names or logos of EOL or any EOL cornerstone institution
    and shall not exploit in any manner its association with EOL or any EOL cornerstone institution
    unless otherwise agreed to in writing by EOL or any EOL cornerstone institution at the time of such
    expiration or termination.
  %p
    Either Party may amend or modify this Agreement by notifying the other Party in writing and with
    the prior written agreement of the other Party. Either Party may withdraw from the Agreement by
    providing written notification to the other Party 90 days in advance of withdrawal. Should
    = partner.full_name
    withdraw from the agreement, EOL will remove
    = partner.full_name
    content within one month.

  %h4
    Contact information
  %address.partner
    %strong= partner.full_name
    %br/
    = partner.homepage
    %br/
    = partner.user.full_name
    %br/
    = partner.user.email

  %address.eol
    %strong
      Encyclopedia of Life
    %br/
    www.eol.org
    %br/
    Cynthia Parr, Species Pages Director
    %br/
    E-mail: parrc@si.edu
    %br/
    Phone: 202.633.8730
    %p
      On behalf of the Smithsonian Institution, representing the EOL for purposes of the day-to-day
      administration of this Agreement.

app/views/content_partners/content_partner_agreements/edit.html.haml
#content_partner_show.site_column
  .main_content
    - if current_user.is_admin?
      = form_for [@partner, @agreement], :url => content_partner_agreement_path do |form|
        %fieldset
          = render 'modify_agreement', { :form => form }
        %fieldset.actions
          = form.submit I18n.t('helpers.submit.content_partner_agreement.update')
          = link_to I18n.t(:content_partner_agreement_cancel_edit_agreement_link), @partner
    - else
      .copy
        %p= raw I18n.t(:content_partner_resources_policy_information)
        = render 'sign_agreement'

app/views/content_partners/content_partner_agreements/new.html.haml
#content_partner_show.site_column
  .main_content
    - if current_user.is_admin?
      = form_for [@partner, @agreement], :url => content_partner_agreements_path do |form|
        %fieldset
          = render 'modify_agreement', { :form => form }
        %fieldset.actions
          = form.submit I18n.t('helpers.submit.content_partner_agreement.update')
          = link_to I18n.t(:content_partner_agreement_cancel_new_agreement_link), @partner
    - else
      .copy
        %p= I18n.t(:content_partner_resources_policy_information)
        = render 'sign_agreement'

app/views/content_partners/content_partner_agreements/show.html.haml
= content_for :page_actions do
  %li= link_to I18n.t(:content_partner_overview_link_back_to), @partner

#content_partner_show.site_column
  .main_content
    .copy
      = raw(@agreement.body)